language: java

batch-size: 512KB

samples:
  - id: IOUtilsTestCase
    script: java -cp target/classes:target/test-classes:$(cat dep.txt) org.junit.runner.JUnitCore org.apache.commons.io.IOUtilsTestCase
  - id: FileUtilsTestCase
    script: java -cp target/classes:target/test-classes:$(cat dep.txt) org.junit.runner.JUnitCore org.apache.commons.io.FileUtilsTestCase
  - id: FilenameUtilsTestCase
    script: java -cp target/classes:target/test-classes:$(cat dep.txt) org.junit.runner.JUnitCore org.apache.commons.io.FilenameUtilsTestCase
  - id: FileSystemUtilsTestCase
    script: java -cp target/classes:target/test-classes:$(cat dep.txt) org.junit.runner.JUnitCore org.apache.commons.io.FileSystemUtilsTestCase
